using GastroErp.Domain.Enums;

namespace GastroErp.Application.Features.Inventory.DTOs;

public record SupplierListItemDto(
    Guid Id,
    string Code,
    string NameAr,
    string? NameEn,
    string? AccountNumber,
    Guid? ApAccountId,
    SupplierCategory Category,
    string? City,
    string? Country,
    string? TaxNumber,
    decimal CreditLimit,
    decimal CurrentBalance,
    DateOnly? LastPurchaseDate,
    DateOnly? LastPaymentDate,
    bool IsActive,
    bool IsBlacklisted,
    bool IsOverCreditLimit);

public record SupplierContactDto(
    Guid Id,
    string NameAr,
    string? NameEn,
    string PhoneNumber,
    string? Mobile,
    string? Email,
    string? Position);

public record SupplierPaymentMethodDto(
    Guid Id,
    SupplierPaymentMethodKind Kind,
    string? BankName,
    string? Iban,
    string? Swift,
    string? AccountNumber,
    string? BeneficiaryName,
    string Currency,
    bool IsDefault,
    string? Notes);

public record SupplierAttachmentDto(
    Guid Id,
    string FileName,
    string ContentType,
    string StoragePath,
    long SizeBytes,
    string? Category,
    DateTimeOffset CreatedAt);

public record SupplierStatsDto(
    int PurchaseOrderCount,
    int GoodsReceiptCount,
    int InvoiceCount,
    int ReturnCount,
    int PaymentCount,
    decimal TotalPurchases,
    decimal PurchasesThisMonth,
    decimal PurchasesThisYear,
    decimal PurchasesLastYear,
    decimal AveragePaymentDays,
    decimal OverdueDays,
    decimal TotalTax,
    decimal CurrentBalance,
    decimal OutstandingBalance,
    DateOnly? LastPurchaseDate,
    DateOnly? LastPaymentDate,
    DateTimeOffset? LastActivityAt);

public record SupplierDashboardDto(
    decimal CurrentBalance,
    int UnpaidInvoiceCount,
    int PurchaseOrderCount,
    int InvoiceCount,
    int ReturnCount,
    int PaymentCount,
    DateOnly? LastPurchaseDate,
    DateOnly? LastPaymentDate,
    bool IsOverCreditLimit,
    bool IsTaxCertificateExpired,
    bool IsCommercialRegisterExpired,
    IReadOnlyList<string> Warnings);

public record SupplierDto(
    Guid Id,
    Guid TenantId,
    Guid? CompanyId,
    Guid? BranchId,
    string Code,
    string NameAr,
    string? NameEn,
    SupplierType SupplierType,
    SupplierCategory Category,
    string? TaxNumber,
    string? CommercialRegister,
    string? EstablishmentNumber,
    string? TaxRegistrationCountry,
    string? TaxType,
    decimal DefaultTaxPercent,
    DateOnly? TaxCertificateExpiry,
    DateOnly? CommercialRegisterExpiry,
    string? TaxCertificatePath,
    string? CommercialRegisterPath,
    string? ContactPerson,
    string? ContactJobTitle,
    string? Phone,
    string? Mobile,
    string? Email,
    string? Website,
    string? City,
    string? Region,
    string? Country,
    string? PostalCode,
    string? Address,
    Guid? ApAccountId,
    string? AccountNumber,
    Guid? DiscountAccountId,
    Guid? PurchaseReturnAccountId,
    Guid? ExchangeDifferenceAccountId,
    string Currency,
    SupplierPaymentMethodKind DefaultPaymentMethod,
    int PaymentDueDays,
    string? PaymentTerms,
    decimal CreditLimit,
    decimal OpeningBalance,
    DateOnly? OpeningBalanceDate,
    SupplierVatEvaluation VatEvaluation,
    int LeadTimeDays,
    bool IsPreferred,
    int Rating,
    bool IsActive,
    bool IsBlacklisted,
    string? BlacklistReason,
    string? Notes,
    decimal CurrentBalance,
    bool IsOverCreditLimit,
    int ContactCount,
    DateTimeOffset CreatedAt,
    IReadOnlyList<SupplierContactDto> Contacts,
    IReadOnlyList<SupplierPaymentMethodDto> PaymentMethods,
    IReadOnlyList<SupplierAttachmentDto> Attachments,
    SupplierDashboardDto? Dashboard = null,
    SupplierStatsDto? Stats = null);

public record CreateSupplierDto(
    Guid TenantId,
    string NameAr,
    Guid ApAccountId,
    string? NameEn = null,
    string? Code = null,
    string Currency = "SAR",
    Guid? CompanyId = null,
    Guid? BranchId = null,
    SupplierType SupplierType = SupplierType.Local,
    SupplierCategory Category = SupplierCategory.Other,
    SupplierPaymentMethodKind DefaultPaymentMethod = SupplierPaymentMethodKind.Credit,
    int PaymentDueDays = 0,
    decimal CreditLimit = 0,
    string? TaxNumber = null,
    string? Phone = null,
    string? Email = null,
    string? City = null,
    string? Country = null,
    string? Address = null,
    string? Notes = null);

public record UpsertSupplierMasterDto(
    string NameAr,
    string? NameEn,
    SupplierType SupplierType,
    SupplierCategory Category,
    Guid? CompanyId,
    Guid? BranchId,
    // Tax
    string? TaxNumber,
    string? CommercialRegister,
    string? EstablishmentNumber,
    string? TaxRegistrationCountry,
    string? TaxType,
    decimal DefaultTaxPercent,
    DateOnly? TaxCertificateExpiry,
    DateOnly? CommercialRegisterExpiry,
    // Contact
    string? ContactPerson,
    string? ContactJobTitle,
    string? Phone,
    string? Mobile,
    string? Email,
    string? Website,
    string? City,
    string? Region,
    string? Country,
    string? PostalCode,
    string? Address,
    // Financial
    Guid ApAccountId,
    Guid? DiscountAccountId,
    Guid? PurchaseReturnAccountId,
    Guid? ExchangeDifferenceAccountId,
    string Currency,
    SupplierPaymentMethodKind DefaultPaymentMethod,
    int PaymentDueDays,
    string? PaymentTerms,
    decimal CreditLimit,
    decimal OpeningBalance,
    DateOnly? OpeningBalanceDate,
    SupplierVatEvaluation VatEvaluation,
    int LeadTimeDays,
    bool IsPreferred,
    int Rating,
    string? Notes,
    IReadOnlyList<SupplierPaymentMethodInputDto>? PaymentMethods = null);

public record SupplierPaymentMethodInputDto(
    SupplierPaymentMethodKind Kind,
    string? BankName = null,
    string? Iban = null,
    string? Swift = null,
    string? AccountNumber = null,
    string? BeneficiaryName = null,
    string Currency = "SAR",
    bool IsDefault = false,
    string? Notes = null);

public record UpdateSupplierDto(string NameAr, string? NameEn = null, string Currency = "SAR");

public record UpdateSupplierFinancialDto(
    string? TaxNumber,
    string? PaymentTerms,
    decimal CreditLimit,
    int LeadTimeDays,
    Guid? ApAccountId = null,
    int PaymentDueDays = 0);

public record AddSupplierContactDto(
    string NameAr,
    string PhoneNumber,
    string? Email = null,
    string? Position = null,
    string? NameEn = null,
    string? Mobile = null);

public record SupplierPurchasingDefaultsDto(
    Guid Id,
    string Code,
    string NameAr,
    Guid? ApAccountId,
    string Currency,
    decimal DefaultTaxPercent,
    int PaymentDueDays,
    string? PaymentTerms,
    SupplierPaymentMethodKind DefaultPaymentMethod,
    decimal CreditLimit,
    decimal CurrentBalance,
    bool IsOverCreditLimit,
    bool IsBlacklisted,
    bool IsActive,
    SupplierPaymentMethodDto? DefaultBankAccount,
    IReadOnlyList<string> Warnings);
