using GastroErp.Domain.Entities.Finance;

namespace GastroErp.Application.Features.Finance.DTOs;

public record CashBoxUserDto(
    Guid? Id,
    Guid UserId,
    string? UserName,
    string? RoleName,
    bool IsDefault,
    bool IsManager,
    bool IsCustodian);

public record CashBoxDeviceDto(
    Guid? Id,
    Guid? DeviceId,
    string? DeviceName,
    CashBoxDeviceRole DeviceRole,
    string? Label);

public record UpsertCashBoxDto(
    string NameAr,
    Guid CompanyId,
    Guid BranchId,
    Guid ChartOfAccountId,
    Guid CurrencyId,
    string? NameEn = null,
    string? LocationName = null,
    Guid? PosDeviceId = null,
    decimal OpeningBalance = 0,
    DateOnly? OpeningDate = null,
    string? Description = null,
    bool IsActive = true,
    bool AllowReceive = true,
    bool AllowPay = true,
    bool AllowDeposit = true,
    bool AllowWithdraw = true,
    bool AllowTransfer = true,
    bool RequireShiftBeforeUse = false,
    bool AllowNegativeBalance = false,
    decimal? MinBalance = null,
    decimal? MaxBalance = null,
    int SortOrder = 0,
    IReadOnlyList<CashBoxUserDto>? AuthorizedUsers = null,
    IReadOnlyList<CashBoxDeviceDto>? Devices = null);

public record CashBoxDto(
    Guid Id,
    int Number,
    string Code,
    string NameAr,
    string? NameEn,
    Guid CompanyId,
    string? CompanyNameAr,
    Guid BranchId,
    string? BranchNameAr,
    string? LocationName,
    Guid? PosDeviceId,
    string? PosDeviceName,
    Guid ChartOfAccountId,
    string? AccountNumber,
    string? AccountNameAr,
    Guid CurrencyId,
    string? CurrencyCode,
    decimal OpeningBalance,
    DateOnly? OpeningDate,
    string? Description,
    bool IsActive,
    bool AllowReceive,
    bool AllowPay,
    bool AllowDeposit,
    bool AllowWithdraw,
    bool AllowTransfer,
    bool RequireShiftBeforeUse,
    bool AllowNegativeBalance,
    decimal? MinBalance,
    decimal? MaxBalance,
    decimal CurrentBalance,
    Guid? CurrentUserId,
    string? CurrentUserName,
    DateTimeOffset? LastOpenedAt,
    DateTimeOffset? LastClosedAt,
    DateTimeOffset? LastMovementAt,
    DateTimeOffset? LastCountAt,
    bool IsOpen,
    bool HasHadMovement,
    bool IsSystem,
    int SortOrder,
    DateTimeOffset CreatedAt,
    string? CreatedBy,
    DateTimeOffset? UpdatedAt,
    string? UpdatedBy,
    IReadOnlyList<CashBoxUserDto> AuthorizedUsers,
    IReadOnlyList<CashBoxDeviceDto> Devices);

public record CashBoxFilterDto(
    Guid? CompanyId = null,
    Guid? BranchId = null,
    Guid? CurrencyId = null,
    bool? IsActive = null,
    string? Search = null,
    int Page = 1,
    int PageSize = 200);
