using GastroErp.Domain.Enums;

namespace GastroErp.Application.Features.Finance.DTOs;

public record DocumentTypeLifecycleStageDto(
    string Code,
    string NameAr,
    string NameEn,
    int SortOrder,
    bool IsTerminal);

public record UpsertDocumentTypeDto(
    string NameAr,
    string NameEn,
    string Code,
    DocumentModule Module,
    string Prefix,
    string? Description = null,
    string? Suffix = null,
    long StartingNumber = 1,
    long LastNumber = 0,
    byte NumberLength = 6,
    bool ResetYearly = false,
    bool ResetMonthly = false,
    bool NumberPerBranch = false,
    bool NumberPerCompany = false,
    DocumentApprovalMode ApprovalMode = DocumentApprovalMode.None,
    bool RequiresApproval = false,
    bool UsesWorkflow = false,
    Guid? WorkflowDefinitionId = null,
    DocumentPostingMode PostingMode = DocumentPostingMode.Manual,
    bool AutoPost = false,
    bool PostAfterApproval = false,
    bool AffectsInventory = false,
    bool AffectsCost = false,
    bool AffectsAccounting = false,
    bool AffectsCash = false,
    bool AffectsCustomers = false,
    bool AffectsSuppliers = false,
    bool AffectsAssets = false,
    bool AffectsPayroll = false,
    bool AllowCreate = true,
    bool AllowUpdate = true,
    bool AllowApprove = true,
    bool AllowPost = true,
    bool AllowCancel = true,
    bool AllowDelete = false,
    bool AllowAttachments = true,
    bool AllowPrint = true,
    bool AllowEditAfterSave = true,
    bool AllowDeleteDocuments = false,
    bool AllowCancelDocuments = true,
    bool AllowCopy = true,
    bool AllowReopen = false,
    bool ShowInReports = true,
    bool ShowInDashboard = false,
    bool IsActive = true,
    int SortOrder = 0,
    IReadOnlyList<DocumentTypeLifecycleStageDto>? LifecycleStages = null);

public record CopyDocumentTypeDto(
    string NewCode,
    string NameAr,
    string NameEn,
    string Prefix);

public record DocumentTypeDto(
    Guid Id,
    string Code,
    string NameAr,
    string NameEn,
    string? Description,
    DocumentModule Module,
    string ModuleCode,
    string Prefix,
    string? Suffix,
    long StartingNumber,
    long LastNumber,
    byte NumberLength,
    bool ResetYearly,
    bool ResetMonthly,
    bool NumberPerBranch,
    bool NumberPerCompany,
    DocumentApprovalMode ApprovalMode,
    bool RequiresApproval,
    bool UsesWorkflow,
    Guid? WorkflowDefinitionId,
    DocumentPostingMode PostingMode,
    bool AutoPost,
    bool PostAfterApproval,
    bool AffectsInventory,
    bool AffectsCost,
    bool AffectsAccounting,
    bool AffectsCash,
    bool AffectsCustomers,
    bool AffectsSuppliers,
    bool AffectsAssets,
    bool AffectsPayroll,
    bool AllowCreate,
    bool AllowUpdate,
    bool AllowApprove,
    bool AllowPost,
    bool AllowCancel,
    bool AllowDelete,
    bool AllowAttachments,
    bool AllowPrint,
    bool AllowEditAfterSave,
    bool AllowDeleteDocuments,
    bool AllowCancelDocuments,
    bool AllowCopy,
    bool AllowReopen,
    bool ShowInReports,
    bool ShowInDashboard,
    bool IsSystem,
    bool IsActive,
    int SortOrder,
    IReadOnlyList<DocumentTypeLifecycleStageDto> LifecycleStages);

public record DocumentTypeFilterDto(
    DocumentModule? Module = null,
    bool? IsActive = null,
    string? Search = null,
    int Page = 1,
    int PageSize = 200);
