using GastroErp.Domain.Entities.Finance;
using GastroErp.Domain.Enums;

namespace GastroErp.Application.Features.Finance.DTOs;

public record FinancialNoteLineDto(
    Guid? Id,
    Guid NotificationReasonId,
    string? ReasonCode,
    string? ReasonNameAr,
    Guid OffsetAccountId,
    string? OffsetAccountNumber,
    string? OffsetAccountNameAr,
    Guid? CostCenterId,
    string? CostCenterNameAr,
    Guid? AnalyticalAccountId,
    string? AnalyticalAccountNameAr,
    string Currency,
    decimal ExchangeRate,
    decimal Amount,
    decimal AmountInBase,
    string? Description);

public record UpsertFinancialNoteDto(
    FinancialNoteKind NoteKind,
    Guid CompanyId,
    Guid BranchId,
    DateOnly NoteDate,
    Guid FiscalPeriodId,
    NotificationPartyType PartyType,
    Guid MainAccountId,
    string Currency = "SAR",
    decimal ExchangeRate = 1m,
    Guid? PartyId = null,
    string? PartyName = null,
    FinancialNoteReferenceType ReferenceType = FinancialNoteReferenceType.None,
    Guid? ReferenceDocumentId = null,
    string? ReferenceNumber = null,
    string? Description = null,
    string? Notes = null,
    IReadOnlyList<FinancialNoteLineDto>? Lines = null);

public record FinancialNoteDto(
    Guid Id,
    int Number,
    string DocumentNumber,
    FinancialNoteKind NoteKind,
    Guid CompanyId,
    string? CompanyNameAr,
    Guid BranchId,
    string? BranchNameAr,
    DateOnly NoteDate,
    Guid FiscalPeriodId,
    int? FiscalYear,
    NotificationPartyType PartyType,
    Guid? PartyId,
    string? PartyName,
    Guid MainAccountId,
    string? MainAccountNumber,
    string? MainAccountNameAr,
    string Currency,
    decimal ExchangeRate,
    FinancialNoteReferenceType ReferenceType,
    Guid? ReferenceDocumentId,
    string? ReferenceNumber,
    string? Description,
    string? Notes,
    FinancialNoteStatus Status,
    Guid? JournalEntryId,
    string? JournalEntryNumber,
    int LinesCount,
    decimal TotalAmount,
    decimal TotalAmountInBase,
    DateTimeOffset CreatedAt,
    DateTimeOffset? PostedAt,
    DateTimeOffset? ApprovedAt,
    IReadOnlyList<FinancialNoteLineDto> Lines);

public record FinancialNoteFilterDto(
    Guid? CompanyId = null,
    Guid? BranchId = null,
    Guid? FiscalPeriodId = null,
    FinancialNoteKind? NoteKind = null,
    FinancialNoteStatus? Status = null,
    NotificationPartyType? PartyType = null,
    Guid? NotificationReasonId = null,
    DateOnly? FromDate = null,
    DateOnly? ToDate = null,
    string? Search = null,
    int Page = 1,
    int PageSize = 200);
