using GastroErp.Domain.Enums;

namespace GastroErp.Application.Features.Finance.DTOs;

public record ReceiptVoucherLineDto(
    Guid? Id,
    Guid ChartOfAccountId,
    string? AccountNumber,
    string? AccountNameAr,
    Guid? CostCenterId,
    string? CostCenterNameAr,
    Guid? AnalyticalAccountId,
    string? AnalyticalAccountNameAr,
    string Currency,
    decimal ExchangeRate,
    decimal Amount,
    decimal AmountInBase,
    string? Description);

public record UpsertReceiptVoucherDto(
    Guid CompanyId,
    Guid BranchId,
    DateOnly VoucherDate,
    Guid FiscalPeriodId,
    ReceiptMethod ReceiptMethod,
    ReceiptPartyType PartyType,
    Guid? CashBoxId = null,
    Guid? BankId = null,
    Guid? PartyId = null,
    string? PartyName = null,
    string Currency = "SAR",
    decimal ExchangeRate = 1m,
    Guid? CostCenterId = null,
    string? Reference = null,
    string? Description = null,
    string? Notes = null,
    string? ChequeNumber = null,
    DateOnly? ChequeDate = null,
    IReadOnlyList<ReceiptVoucherLineDto>? Lines = null);

public record ReceiptVoucherDto(
    Guid Id,
    int Number,
    string DocumentNumber,
    Guid CompanyId,
    string? CompanyNameAr,
    Guid BranchId,
    string? BranchNameAr,
    DateOnly VoucherDate,
    Guid FiscalPeriodId,
    int? FiscalYear,
    ReceiptMethod ReceiptMethod,
    Guid? CashBoxId,
    string? CashBoxNameAr,
    Guid? BankId,
    string? BankNameAr,
    ReceiptPartyType PartyType,
    Guid? PartyId,
    string? PartyName,
    string Currency,
    decimal ExchangeRate,
    Guid? CostCenterId,
    string? CostCenterNameAr,
    string? Reference,
    string? ChequeNumber,
    DateOnly? ChequeDate,
    string? Description,
    string? Notes,
    ReceiptVoucherStatus Status,
    Guid? JournalEntryId,
    string? JournalEntryNumber,
    int LinesCount,
    decimal TotalAmount,
    decimal TotalAmountInBase,
    DateTimeOffset CreatedAt,
    DateTimeOffset? PostedAt,
    DateTimeOffset? ApprovedAt,
    IReadOnlyList<ReceiptVoucherLineDto> Lines);

public record ReceiptVoucherFilterDto(
    Guid? CompanyId = null,
    Guid? BranchId = null,
    Guid? FiscalPeriodId = null,
    ReceiptVoucherStatus? Status = null,
    ReceiptMethod? ReceiptMethod = null,
    Guid? CashBoxId = null,
    Guid? BankId = null,
    string? Currency = null,
    DateOnly? FromDate = null,
    DateOnly? ToDate = null,
    string? Search = null,
    int Page = 1,
    int PageSize = 200);
